name: deflow
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - pytorch::pytorch=2.0.0
  - pytorch::torchvision
  - pytorch::pytorch-cuda=11.7
  - lightning==2.0.1
  - nvidia::cudatoolkit=11.7
  - numba
  - numpy
  - pandas
  - pip
  - scipy
  - tqdm
  - h5py
  - wandb
  - omegaconf
  - hydra-core
  - fire
  - tabulate
  - pip:
    - open3d==0.16.0
    - dztimer
    - av2
    - linefit

# Reason about the version fixed:
# lightning==2.0.1: https://stackoverflow.com/questions/76647518/how-to-fix-error-cannot-import-name-modelmetaclass-from-pydantic-main
# open3d==0.16.0: because 0.17.0 have bug on set the view json file
